### ISSUE TITLE
Prefill terminology codes from CSV file

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-frontend#317]
# Description
Adding a large set of terminology codes to a phenotype can become cumbersome. We should add an option to upload a CSV file of codes, that will be automatically appended to the code list.

# TODOs

- [x] add select field to set `Code.scope` property (default value is 'self')
- [x] display scope in code list
- [x] decide on CSV format
- [x] add CSV import (drag-and-drop possible?)
- [x] update documentation

# Other important information

Entries from the CSV will be transformed into JSON objects and appended to the code list - without any checks. The backend should perform additional requests to the terminology server, if applicable (i.e. label is missing or scope != 'self').
